version: '3.8'
services:
  dotnet:
    build: ./FoodApp-backend
    container_name: dotnet_c
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "8080:80"

  react:
    build: ./FoodApp-frontend
    container_name: react_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true


